# backend/main_app/ai_service.py
import os
import google.generativeai as genai
from django.conf import settings

genai.configure(api_key=settings.GEMINI_API_KEY)

def suggest_mission(event_title, event_location, event_date):
    prompt = f"""
    You are an AI event planner. Suggest ONE creative mission for this event:
    - Title: {event_title}
    - Location: {event_location}
    - Date: {event_date}
    
    Return only: title and short description. Format: 
    Title: [title]
    Description: [description]
    """
    model = genai.GenerativeModel('gemini-1.5-flash')
    response = model.generate_content(prompt)
    text = response.text.strip()
    
    try:
        title = text.split("Title:")[1].split("Description:")[0].strip()
        desc = text.split("Description:")[1].strip()
    except:
        title = "AI Mission"
        desc = "Auto-generated by Gemini"
    
    return {"title": title, "description": desc}

def split_mission(mission_title, mission_desc, team_members):
    member_names = [m.user.username for m in team_members]
    prompt = f"""
    Split this mission into {len(member_names)} subtasks (one per member):
    Mission: {mission_title}
    Description: {mission_desc}
    Team: {', '.join(member_names)}
    
    Return JSON list: [{"title": "...", "assignee": "name"}]
    """
    model = genai.GenerativeModel('gemini-1.5-flash')
    response = model.generate_content(prompt)
    try:
        import json
        subtasks = json.loads(response.text.strip('```json').strip('```'))
        return subtasks
    except:
        return []