# Generated by Django 5.2.7 on 2025-11-04 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_task_ai_generated_task_approved_task_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main_app.company'),
        ),
    ]
