# Generated by Django 5.2.7 on 2025-11-04 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_company_created_by_alter_event_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mission',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_missions', to='main_app.userprofile'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_by_ai',
            field=models.BooleanField(default=False),
        ),
    ]
