# Generated by Django 5.2.7 on 2025-11-04 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_mission_assigned_manager_task_assigned_by_ai'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='approved',
            new_name='is_approved',
        ),
        migrations.RemoveField(
            model_name='task',
            name='approved',
        ),
    ]
