# Generated by Django 5.2.7 on 2025-11-04 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_rename_approved_mission_is_approved_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mission',
            old_name='ai_generated',
            new_name='ai_split',
        ),
    ]
