# Generated by Django 5.2.7 on 2025-11-04 21:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_rename_ai_generated_mission_ai_split'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='assigned_by_ai',
        ),
    ]
